### PR TITLE
Resnet18 example

### PR DESCRIPTION
**Pull request by dfdx**
Finally, we can load and use at least one real ONNX model! To test it, run:

```
cd examples
julia resnet18.jl
```
Output for the two sample images ([1][1], [2][2]):

```
Loading the model
Image of a guitar
1: acoustic guitar (14.4934225)
2: syringe (12.063086)
3: stage (10.573396)
4: electric guitar (10.417194)
5: microphone, mike (10.33393)
6: pick, plectrum, plectron (10.197258)
7: banjo (10.180879)
8: beaker (9.784172)
9: mousetrap (9.320241)
10: screw (9.16933)

Image of a goose
1: goose (14.918747)
2: crane (11.872782)
3: flamingo (11.383375)
4: spoonbill (11.074749)
5: white stork, Ciconia ciconia (10.853802)
6: American egret, great white heron, Egretta albus (10.148649)
7: pelican (10.008485)
8: bustard (9.508819)
9: peacock (9.446865)
10: black swan, Cygnus atratus (8.912123)
```

[1]: https://cdn.pixabay.com/photo/2015/05/07/11/02/guitar-756326_960_720.jpg
[2]: https://upload.wikimedia.org/wikipedia/commons/3/3f/Snow_goose_2.jpg

### CODE REVIEW

**Comment by lpiert** [comment]
you are sure it is ok ?  I had a error info " ERROR: LoadError: cannot read wire type 2 as int64
"
env: julia  1.7.0

**Comment by lpiert** [comment]
you are sure it is ok ? I had a error info " ERROR: LoadError: cannot read wire type 2 as int64
"
env: julia 1.7.0

julia 1.6.0 wiil get error "no load methed.  ONNX only has load_mode(...)"

**Comment by dfdx** [comment]
Just to make sure, are you on the `main` branch?

**Comment by lpiert** [comment]
> Just to make sure, are you on the `main` branch?

Yes, I tried julia 1.6 1.7 and there will be errors. May I ask what version of julia did you run through?

**Comment by lpiert** [comment]
> Just to make sure, are you on the `main` branch?

yes.  I had check my env with "https://github.com/FluxML/ONNX.jl/runs/4692195324?check_suite_focus=true"   but untill now it can not pass. include julia 1.6.5 with ONNX.jl  master.

**Comment by dfdx** [comment]
Could you please post the exact instructions you used to run the example? For me, it works on both - Julia 1.7.0 and 1.6.2:

```
~/work/ONNX.jl/examples$ julia resnet18.jl 
  Activating project at `~/work/ONNX.jl`
Loading the model
Image of a guitar:
1: acoustic guitar (14.368217)
2: syringe (12.29585)
3: stage (10.622771)
4: electric guitar (10.400158)
5: microphone, mike (10.216346)
6: pick, plectrum, plectron (10.194254)
7: banjo (10.128281)
8: beaker (9.8587475)
9: mousetrap (9.248266)
10: screw (8.919548)

Image of a goose:
1: goose (14.927252)
2: crane (11.862922)
3: flamingo (11.377805)
4: spoonbill (11.055642)
5: white stork, Ciconia ciconia (10.838628)
6: American egret, great white heron, Egretta albus (10.136587)
7: pelican (10.013964)
8: bustard (9.5049715)
9: peacock (9.447408)
10: albatross, mollymawk (8.912547)
```
Also, the errors you posted seem to belong to earlier versions of ONNX.jl. For example, if you type "load_mode" in the GitHub's search box, there are no results, so this function comes from somewhere else.

**Comment by ToucheSir** [comment]
> it's the same problem " #43" It hasn't been fixed until now.

It is not, because the _entire_ codebase has changed since then. If you post the entire stacktrace (use triple backticks, ```, for code blocks), we can confirm that you're running the correct version of the library code.

**Comment by dfdx** [comment]
Please, make sure that you are not only in the `ONNX.jl` directory on git master branch, but also that Julia is running in an environment with `ONNX#master`. You can ensure it for example like this:

```julia
# bash
cd ~/ONNX.jl
julia

# julia REPL
] activate .  # activate the environment in the current directory
cd("examples")
include("resnet18.jl")
```
or like this:

```julia
# bash
cd ~/ONNX.jl/examples
julia

# julia REPL
] add ONNX#master   # install ONNX at master in whatever environment is currently active
exit()

# bash
julia resent18.jl
```

**Comment by lpiert** [comment]
> cannot read wire type 2 as int64

Stacktrace:
  [1] error(s::String)
    @ Base ./error.jl:33
  [2] read_field(io::IOStream, container::ModelProto, attrib::ProtoBuf.ProtoMetaAttribs, wiretyp::UInt64, jtyp_specific::Nothing)
    @ ProtoBuf ~/.julia/packages/ProtoBuf/l7nsO/src/codec.jl:495
  [3] readproto(io::IOStream, obj::ModelProto, meta::ProtoBuf.ProtoMeta)
    @ ProtoBuf ~/.julia/packages/ProtoBuf/l7nsO/src/codec.jl:527
  [4] readproto
    @ ~/.julia/packages/ProtoBuf/l7nsO/src/codec.jl:511 [inlined]
  [5] load(io::IOStream, args::Array{Float32, 4}; backends::Vector{Symbol}, exec::Bool)
    @ ONNX ~/.julia/packages/ONNX/TEIEp/src/load.jl:160
  [6] #123
    @ ~/.julia/packages/ONNX/TEIEp/src/load.jl:226 [inlined]
  [7] open(f::ONNX.var"#123#124"{Vector{Symbol}, Bool, Tuple{Array{Float32, 4}}}, args::String; kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Base ./io.jl:330
  [8] open
    @ ./io.jl:328 [inlined]
  [9] #load#122
    @ ~/.julia/packages/ONNX/TEIEp/src/load.jl:225 [inlined]
 [10] load(filename::String, args::Array{Float32, 4})
    @ ONNX ~/.julia/packages/ONNX/TEIEp/src/load.jl:225
 [11] top-level scope
    @ In[10]:1
 [12] eval
    @ ./boot.jl:373 [inlined]
 [13] include_string(mapexpr::typeof(REPL.softscope), mod::Module, code::String, filename::String)
    @ Base ./loading.jl:1196

**Comment by dfdx** [comment]
Can you please check that `resnet18.onnx` is downloaded correctly to `ONNX.jl/examples`. The example tries to download the file once and reuse it in subsequent calls. But if there was a network error or similar, you may get text file with error description instead. 

As a workaround, you can also download [the model file](https://github.com/onnx/models/raw/main/vision/classification/resnet/model/resnet18-v1-7.onnx) manually and put to `ONNX.jl/examples` directory, and then read run the example again.

**Comment by lpiert** [comment]
> Can you please check that `resnet18.onnx` is downloaded correctly to `ONNX.jl/examples`. The example tries to download the file once and reuse it in subsequent calls. But if there was a network error or similar, you may get text file with error description instead.
> 
> As a workaround, you can also download [the model file](https://github.com/onnx/models/raw/main/vision/classification/resnet/model/resnet18-v1-7.onnx) manually and put to `ONNX.jl/examples` directory, and then read run the example again.

Thanks.  I had fixed these by ONNXRuntime pkg.

**Comment by lpiert** [comment]
> Can you please check that `resnet18.onnx` is downloaded correctly to `ONNX.jl/examples`. The example tries to download the file once and reuse it in subsequent calls. But if there was a network error or similar, you may get text file with error description instead.
> 
> As a workaround, you can also download [the model file](https://github.com/onnx/models/raw/main/vision/classification/resnet/model/resnet18-v1-7.onnx) manually and put to `ONNX.jl/examples` directory, and then read run the example again.

Thanks for you support. I've solved my problem use the ONNXRuntime package.

**Comment by jbrea** [comment]
I had to change the path to `https://github.com/onnx/models/raw/main/vision/classification/resnet/model/resnet18-v1-7.onnx` to download the correct file.

**Comment by dfdx** [comment]
Thanks for the tip! I've updated the model URL in `master`.

**Pull request merged**
